import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Layout } from '../components/layout'
import styles from '../styles/Home.module.css'
import flashcardTypes from "../components/layout"
import Link from "next/link"



const Home: NextPage = () => {
  return (
    <Layout>
    <div className={styles.container}>
      <Head>
        <title>Flashcards games</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <br></br> flashcard games !
        </h1>
        <p></p>
        <h3 >
          Pick your game
        </h3>


        <div className={styles.grid}>
          <Link href="/flashcards/mental-cards" >
            <a className={styles.card}>
              <h2>Mental Cards &rarr;</h2>
              <p>The most simple one, click on the question to get the answer</p>
            </a>
          </Link>

          <Link href="/flashcards/input">
            <a className={styles.card}>
              <h2>Input cards &rarr;</h2>
              <p>Enter the right answer in the designated field and check if you are a genius</p>
            </a>
          </Link>

          <Link href="/flashcards/multiple-choice">
            <a className={styles.card}>
              <h2>Multiple-choice cards &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>
          </Link>

          <Link href="/flashcards/salade">
            <a className={styles.card}>
            <h2>Salade &rarr;</h2>
            <p>
              Still hesitating on the game to pick ? The salad is a random mix of all of them !
            </p>
          </a>
        </Link>
        </div>
      </main>
    </div>
    </Layout>
  )
}

export default Home
